"""Column names shared by synthetic CSV export and database import."""

CSV_COLUMN_LABELS = {
    "id": "идентификатор",
    "project_id": "идентификатор_проекта",
    "name": "название",
    "lifecycle_status": "жизненный_статус",
    "priority": "приоритет",
    "start_date": "дата_старта",
    "planned_end_date": "плановая_дата_окончания",
    "business_goal": "бизнес_цель",
    "expected_result": "ожидаемый_результат",
    "business_value": "бизнес_ценность",
    "external_id": "внешний_идентификатор",
    "title": "заголовок",
    "assignee_id": "идентификатор_исполнителя",
    "assignee_name": "исполнитель",
    "status": "статус",
    "planned_due_date": "плановый_срок",
    "actual_end_date": "фактическая_дата_завершения",
    "estimated_hours": "оценка_часов",
    "spent_hours": "затрачено_часов",
    "is_blocked": "заблокирована",
    "blocker_reason": "причина_блокировки",
    "task_id": "идентификатор_задачи",
    "changed_at": "время_изменения",
    "field_changed": "измененное_поле",
    "old_value": "старое_значение",
    "new_value": "новое_значение",
    "changed_by": "кем_изменено",
    "source_system": "система_источник",
    "author_id": "идентификатор_автора",
    "author_name": "автор",
    "created_at": "время_создания",
    "channel": "канал",
    "text": "текст",
    "mentions_count": "количество_упоминаний",
    "planned_start_date": "плановая_дата_начала",
    "actual_start_date": "фактическая_дата_начала",
    "responsible_team": "ответственная_команда",
    "planned_budget": "плановый_бюджет",
    "actual_spent": "фактические_затраты",
    "expected_economic_effect": "ожидаемый_экономический_эффект",
    "cost_of_delay_per_day": "стоимость_дня_задержки",
    "currency": "валюта",
    "risk_type": "тип_риска",
    "description": "описание",
    "probability": "вероятность",
    "impact": "влияние",
    "owner_name": "ответственный",
    "mitigation_plan": "план_снижения_риска",
    "linked_task_id": "идентификатор_связанной_задачи",
    "from_team": "команда_отправитель",
    "to_team": "команда_получатель",
    "topic": "тема",
    "last_message_date": "дата_последнего_сообщения",
    "expected_response_date": "ожидаемая_дата_ответа",
    "importance": "важность",
    "full_name": "фио",
    "role": "роль",
    "team": "команда",
    "available_hours_per_week": "доступно_часов_в_неделю",
    "hour_rate": "часовая_ставка",
    "seniority": "уровень_специалиста",
    "resource_id": "идентификатор_ресурса",
    "planned_hours_per_week": "план_часов_в_неделю",
    "actual_hours_per_week": "факт_часов_в_неделю",
    "depends_on_task_id": "идентификатор_задачи_предшественника",
    "dependency_type": "тип_зависимости",
    "is_critical_path": "критический_путь",
    "lag_days": "лаг_дней",
    "reason": "причина",
    "budget_id": "идентификатор_бюджета",
    "category": "категория",
    "item_name": "название_статьи",
    "planned_amount": "плановая_сумма",
    "actual_amount": "фактическая_сумма",
    "owner_team": "команда_владелец",
    "communication_id": "идентификатор_коммуникации",
    "message_time": "время_сообщения",
    "sender_team": "команда_автор_сообщения",
    "recipient_team": "команда_адресат_сообщения",
    "message_type": "тип_сообщения",
    "summary": "краткое_содержание",
    "is_escalation": "эскалация",
    "depends_on": "объект_зависимости",
    "expected_date": "ожидаемая_дата",
    "criticality": "критичность",
    "decision_date": "дата_решения",
    "decision_type": "тип_решения",
    "decision_owner": "владелец_решения",
    "linked_milestone_id": "идентификатор_связанной_вехи",
    "request_date": "дата_запроса",
    "requested_by": "инициатор",
    "change_type": "тип_изменения",
    "requested_budget_delta": "запрошенное_изменение_бюджета",
    "requested_timeline_delta_days": "запрошенное_изменение_срока_дней",
}

CSV_BOOLEAN_COLUMNS = {"is_blocked", "is_critical_path", "is_escalation"}

TASK_HISTORY_FIELD_LABELS = {
    "status": "статус",
    "blocker_reason": "причина блокировки",
    "planned_due_date": "плановый срок",
    "estimated_hours": "оценка часов",
    "spent_hours": "затрачено часов",
    "assignee_id": "исполнитель",
}


TABLE_COLUMNS = {
    "budget_line_items": (
        "id",
        "project_id",
        "budget_id",
        "category",
        "item_name",
        "planned_amount",
        "actual_amount",
        "owner_team",
    ),
    "budgets": (
        "id",
        "project_id",
        "planned_budget",
        "actual_spent",
        "expected_economic_effect",
        "cost_of_delay_per_day",
        "currency",
    ),
    "change_requests": (
        "id",
        "project_id",
        "request_date",
        "requested_by",
        "change_type",
        "description",
        "requested_budget_delta",
        "requested_timeline_delta_days",
        "status",
    ),
    "communication_messages": (
        "id",
        "project_id",
        "communication_id",
        "message_time",
        "sender_team",
        "recipient_team",
        "channel",
        "message_type",
        "status",
        "summary",
        "linked_task_id",
        "is_escalation",
    ),
    "communications": (
        "id",
        "project_id",
        "from_team",
        "to_team",
        "topic",
        "channel",
        "last_message_date",
        "expected_response_date",
        "status",
        "importance",
        "linked_task_id",
    ),
    "decisions": (
        "id",
        "project_id",
        "decision_date",
        "decision_type",
        "description",
        "decision_owner",
        "status",
        "linked_milestone_id",
    ),
    "dependencies": (
        "id",
        "project_id",
        "dependency_type",
        "depends_on",
        "owner_team",
        "expected_date",
        "status",
        "criticality",
        "linked_task_id",
    ),
    "milestones": (
        "id",
        "project_id",
        "name",
        "planned_start_date",
        "planned_end_date",
        "actual_start_date",
        "actual_end_date",
        "status",
        "responsible_team",
    ),
    "projects": (
        "id",
        "name",
        "lifecycle_status",
        "priority",
        "start_date",
        "planned_end_date",
        "business_goal",
        "expected_result",
        "business_value",
    ),
    "resource_allocations": (
        "id",
        "resource_id",
        "project_id",
        "planned_hours_per_week",
        "actual_hours_per_week",
    ),
    "resources": (
        "id",
        "full_name",
        "role",
        "team",
        "available_hours_per_week",
        "hour_rate",
        "seniority",
    ),
    "risks": (
        "id",
        "project_id",
        "risk_type",
        "description",
        "probability",
        "impact",
        "owner_name",
        "mitigation_plan",
        "status",
        "linked_task_id",
    ),
    "task_comments": (
        "id",
        "project_id",
        "task_id",
        "author_id",
        "author_name",
        "created_at",
        "channel",
        "text",
        "mentions_count",
        "source_system",
    ),
    "task_dependencies": (
        "id",
        "project_id",
        "task_id",
        "depends_on_task_id",
        "dependency_type",
        "is_critical_path",
        "lag_days",
        "reason",
    ),
    "task_history": (
        "id",
        "project_id",
        "task_id",
        "changed_at",
        "field_changed",
        "old_value",
        "new_value",
        "changed_by",
        "source_system",
    ),
    "tasks": (
        "id",
        "project_id",
        "external_id",
        "title",
        "assignee_id",
        "assignee_name",
        "status",
        "priority",
        "planned_due_date",
        "actual_end_date",
        "estimated_hours",
        "spent_hours",
        "is_blocked",
        "blocker_reason",
    ),
}
